// ═══════════════════════════════════════════════════════════════
// ENTERPRISE CSM ENGAGEMENT — MAY 2026 DAILY REPORTS
// Generated by automated Weflow scan · Source: Weflow MCP
// ═══════════════════════════════════════════════════════════════

// ─── MAY 1, 2026 ───────────────────────────────────────────────

function dayData_2026_05_01() {
  return {
    calls: [
      { ts: 'May 1 · 2:00 PM',  csm: 'nick',  account: 'Red Hat',          note: 'IT spend hierarchy · AI agents roadmap · IBM time series POC', mins: 60, health: 'Healthy' },
      { ts: 'May 1 · 3:00 PM',  csm: 'rani',  account: 'Cisco',             note: 'Install base + intent · market prediction model · time series demo', mins: 30, health: 'Healthy', xcov: 'pam' },
      { ts: 'May 1 · 4:30 PM',  csm: 'rani',  account: 'Hitachi Vantara',   note: 'QBR prep May 13 · renewal timelines · MCP expansion', mins: 30, health: 'Concerning' },
    ],
    pulses: [
      { csm: 'nick',  account: 'Red Hat',        health: 'Healthy',    note: 'IT spend hierarchy · AI agents roadmap · IBM time series POC' },
      { csm: 'rani',  account: 'Cisco',           health: 'Healthy',    note: 'X-cov for Pam: install base + intent data · time series demo' },
      { csm: 'rani',  account: 'Hitachi Vantara', health: 'Concerning', note: 'QBR May 13 · renewal consolidation · MCP expansion positioned' },
    ],
  };
}

function dayMeta_2026_05_01() {
  return {
    pills: [['dot-teal','3 Calls'],['dot-green','3 Vitally Pulses'],['dot-purple','1 Pending Transcript'],['dot-amber','1 Cross-Coverage']],
    tabs:  ['Overview','Calls (4)','Notes (3)','Action Items (3)'],
  };
}

function dayOverviewHTML_2026_05_01() {
  return `<div class="section-label">Team Activity &mdash; Friday May 1, 2026</div>
  <div class="overview-grid">
    <div class="csm-card has-calls" data-csm="nick"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-grey">NJ</div><div><div class="csm-name">Nick Johnson</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">60m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Red Hat &middot; IT spend hierarchy &middot; AI agents roadmap &middot; IBM time series POC</div></div>
    <div class="csm-card has-calls" data-csm="rani"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">RG</div><div><div class="csm-name">Rani Guy</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">60m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Cisco (X-cov for Pam) &middot; Hitachi Vantara QBR prep</div></div>
    <div class="csm-card no-calls" data-csm="pam"><div class="csm-card-header"><div class="avatar av-grey">PH</div><div><div class="csm-name">Pam Huck</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Cisco covered by Rani Guy on May 1</div></div>
    <div class="csm-card no-calls" data-csm="andy"><div class="csm-card-header"><div class="avatar av-grey">AL</div><div><div class="csm-name">Andy Lim</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">ADP recording found &mdash; transcript pending at scan time, not counted</div></div>
    <div class="csm-card no-calls" data-csm="atisha"><div class="csm-card-header"><div class="avatar av-grey">AW</div><div><div class="csm-name">Atisha Waghela</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-csm="divyam"><div class="csm-card-header"><div class="avatar av-divyam">DD</div><div><div class="csm-name">Divyam Dewan</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Adobe &amp; BILL recordings found &mdash; Divyam not present in transcripts</div></div>
    <div class="csm-card no-calls" data-csm="varun"><div class="csm-card-header"><div class="avatar av-varun">VT</div><div><div class="csm-name">Varun Tiwari</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-csm="riley"><div class="csm-card-header"><div class="avatar av-riley">RR</div><div><div class="csm-name">Riley Rogers</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
  </div>`;
}

function dayCallsHTML_2026_05_01() {
  return `<div class="table-card"><table>
    <thead><tr><th>Time (PT)</th><th>CSM</th><th>Account</th><th>Duration</th><th>Signal</th></tr></thead>
    <tbody>
      <tr data-csm="nick" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 2:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">NJ</div>Nick Johnson</div></td><td><strong>Red Hat</strong> <span style="font-size:11px;color:#9ca3af">IT spend hierarchy &middot; AI agents roadmap &middot; IBM time series POC</span></td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="rani" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">RG</div>Rani Guy <span style="font-size:11px">(X-cov for PH)</span></div></td><td><strong>Cisco</strong> <span style="font-size:11px;color:#9ca3af">Install base + intent data &middot; market prediction model &middot; time series demo</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="rani" data-health="Concerning"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 4:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">RG</div>Rani Guy</div></td><td><strong>Hitachi Vantara</strong> <span style="font-size:11px;color:#9ca3af">QBR prep May 13 &middot; renewal timelines &middot; MCP expansion</span></td><td>30 min</td><td><span class="badge badge-concerning">&#128993; Concerning</span></td></tr>
      <tr data-csm="andy" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">AL</div>Andy Lim</div></td><td><strong>ADP</strong> <span style="font-size:11px;color:#9ca3af">Transcript pending at scan time &mdash; not counted</span></td><td>30 min</td><td><span class="badge" style="background:#fef3c7;color:#92400e">&#128336; Pending</span></td></tr>
    </tbody>
  </table></div>
  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-left:3px solid #3b82f6;border-radius:6px;padding:10px 14px;margin:10px 0;font-size:12px;color:#1e40af;">
    &#x2139;&#xfe0f; <strong>1 cross-coverage call</strong>: Rani Guy covered Cisco (3:00 PM) for Pam Huck. &nbsp;|&nbsp; <strong>1 pending transcript</strong>: ADP (Andy Lim, 3:00 PM) &mdash; still processing at scan time, not counted. &nbsp;|&nbsp; <strong>4 excluded</strong>: Adobe (TrustRadius team), BILL/Udemy (mis-attributed, external call), SAP Ariba/Fieldglass (TrustRadius team), SAP GEO Qs &amp; SAP SuccessFactors (no transcript).
  </div>
  <div class="empty-state" id="calls-empty" style="display:none"><div class="empty-icon">&#128269;</div>No calls match these filters.</div>`;
}

function dayPulsesHTML_2026_05_01() {
  const cards = [
    { csm:'nick',  health:'Healthy',    account:'Red Hat',          opp:'Vitally Pulse &mdash; May 1 Call',  arr:'Enterprise &middot; Nick Johnson',  excerpt:'IT spend hierarchy updates and data taxonomy alignment for wallet share project. AI agents roadmap discussion &mdash; HG data integration into AI pipelines. IBM time series POC progress reviewed. PO still in-flight; delivery cadence paused. Weflow rec: a76RN0000002Kp3YAE', csmlbl:'Nick Johnson', change:'New &middot; Pulse 24e82773' },
    { csm:'rani',  health:'Healthy',    account:'Cisco (WarRoom)',  opp:'Vitally Pulse &mdash; May 1 X-cov', arr:'Enterprise &middot; Rani Guy (covering Pam Huck)', excerpt:'X-cov for Pam Huck: Install base + intent data for Cisco&apos;s internal market prediction model. Buyer intent signal layering strategy. Time series data demo. API access requirements reviewed. Weflow rec: a76RN0000002Ey9YAE', csmlbl:'Rani Guy', change:'New &middot; Pulse 860082c1' },
    { csm:'rani',  health:'Concerning', account:'Hitachi Vantara',  opp:'Vitally Pulse &mdash; May 1 Call',  arr:'Enterprise &middot; Rani Guy',         excerpt:'QBR scheduled May 13 (Anders + Miguel). Renewal timeline alignment: intent Sep 28 &amp; install/spend Oct 22 &mdash; consolidation into single contract discussed. Phoenix/MCP expansion positioned. V3 intent migration progress reviewed. Weflow rec: a76RN0000002COTYA2', csmlbl:'Rani Guy', change:'New &middot; Pulse 164b69eb' },
  ];
  const bc = h => h==='Healthy'?'badge-healthy':'badge-concerning';
  const bi = h => h==='Healthy'?'&#128994;':'&#128993;';
  return `<div class="pulse-grid">${cards.map(c=>`
    <div class="pulse-card" data-csm="${c.csm}" data-health="${c.health}">
      <div class="pulse-card-top"><div><div class="pulse-account">${c.account}</div><div class="pulse-opp">${c.opp}</div><div class="pulse-arr">${c.arr}</div></div><span class="badge ${bc(c.health)}">${bi(c.health)} ${c.health}</span></div>
      <div class="pulse-excerpt">${c.excerpt}</div>
      <div class="pulse-footer"><span>${c.csmlbl}</span><span>${c.change}</span></div>
    </div>`).join('')}</div>
  <div class="empty-state" id="pulses-empty" style="display:none"><div class="empty-icon">&#128269;</div>No pulses match these filters.</div>`;
}

function dayActionsHTML_2026_05_01() {
  return `<div class="action-list">
    <div class="action-item ${doneActions.has(101)?'done':''}" data-csm="rani" id="action-101"><div class="action-checkbox ${doneActions.has(101)?'checked':''}" onclick="toggleAction(101)"></div><div class="action-body"><div class="action-title">&#x26a0;&#xfe0f; Hitachi Vantara QBR &mdash; May 13 with Anders + Miguel</div><div class="action-meta"><span class="urgency-badge urgency-high">TIME-SENSITIVE</span>Rani Guy &middot; QBR confirmed for May 13. Agenda should cover: renewal consolidation (intent Sep 28 + install Oct 22 into single contract), Phoenix/MCP expansion demo, V3 intent migration status. Ensure Anders (VP/decision-maker) is confirmed as attendee.</div></div></div>
    <div class="action-item ${doneActions.has(102)?'done':''}" data-csm="nick" id="action-102"><div class="action-checkbox ${doneActions.has(102)?'checked':''}" onclick="toggleAction(102)"></div><div class="action-body"><div class="action-title">&#x1F4CB; Red Hat PO follow-up &mdash; delivery cadence paused</div><div class="action-meta"><span class="urgency-badge urgency-medium">MEDIUM</span>Nick Johnson &middot; Data delivery paused pending PO clearance from Red Hat procurement. Chase Nick Dietsch on PO status. Note: IBM involvement in Red Hat renewal adds complexity. Maintain biweekly cadence while PO resolves.</div></div></div>
    <div class="action-item ${doneActions.has(103)?'done':''}" data-csm="andy" id="action-103"><div class="action-checkbox ${doneActions.has(103)?'checked':''}" onclick="toggleAction(103)"></div><div class="action-body"><div class="action-title">&#x23F3; ADP transcript pending &mdash; Andy Lim</div><div class="action-meta"><span class="urgency-badge urgency-low">FOLLOW-UP</span>Andy Lim &middot; ADP recording (May 1, 3:00 PM, 30 min) had no transcript at scan time. Check Weflow rec a76RN0000002KInYAM once transcript is available. Create Vitally note and count call if Andy confirmed as speaker.</div></div></div>
  </div>
  <div class="empty-state" id="actions-empty" style="display:none"><div class="empty-icon">&#128269;</div>No action items match these filters.</div>`;
}
