// ═══════════════════════════════════════════════════════════════
// ENTERPRISE CSM ENGAGEMENT — MAY 2026 DAILY REPORTS
// Generated by automated Weflow scan · Source: Weflow MCP
// ═══════════════════════════════════════════════════════════════

// ─── MAY 1, 2026 ───────────────────────────────────────────────

function dayData_2026_05_01() {
  return {
    calls: [
      { ts: 'May 1 · 2:00 PM',  csm: 'nick',  account: 'Red Hat',          note: 'IT spend hierarchy · AI agents roadmap · IBM time series POC', mins: 60, health: 'Healthy' },
      { ts: 'May 1 · 3:00 PM',  csm: 'rani',  account: 'Cisco',             note: 'Install base + intent · market prediction model · time series demo', mins: 30, health: 'Healthy', xcov: 'pam' },
      { ts: 'May 1 · 4:30 PM',  csm: 'rani',  account: 'Hitachi Vantara',   note: 'QBR prep May 13 · renewal timelines · MCP expansion', mins: 30, health: 'Concerning' },
    ],
    pulses: [
      { csm: 'nick',  account: 'Red Hat',        health: 'Healthy',    note: 'IT spend hierarchy · AI agents roadmap · IBM time series POC' },
      { csm: 'rani',  account: 'Cisco',           health: 'Healthy',    note: 'X-cov for Pam: install base + intent data · time series demo' },
      { csm: 'rani',  account: 'Hitachi Vantara', health: 'Concerning', note: 'QBR May 13 · renewal consolidation · MCP expansion positioned' },
    ],
  };
}

function dayMeta_2026_05_01() {
  return {
    pills: [['dot-teal','3 Calls'],['dot-green','3 Vitally Pulses'],['dot-purple','1 Pending Transcript'],['dot-amber','1 Cross-Coverage']],
    tabs:  ['Overview','Calls (4)','Notes (3)','Action Items (3)'],
  };
}

function dayOverviewHTML_2026_05_01() {
  return `<div class="section-label">Team Activity &mdash; Friday May 1, 2026</div>
  <div class="overview-grid">
    <div class="csm-card has-calls" data-csm="nick"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-grey">NJ</div><div><div class="csm-name">Nick Johnson</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">60m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Red Hat &middot; IT spend hierarchy &middot; AI agents roadmap &middot; IBM time series POC</div></div>
    <div class="csm-card has-calls" data-csm="rani"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">RG</div><div><div class="csm-name">Rani Guy</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">60m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Cisco (X-cov for Pam) &middot; Hitachi Vantara QBR prep</div></div>
    <div class="csm-card no-calls" data-csm="pam"><div class="csm-card-header"><div class="avatar av-grey">PH</div><div><div class="csm-name">Pam Huck</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Cisco covered by Rani Guy on May 1</div></div>
    <div class="csm-card no-calls" data-csm="andy"><div class="csm-card-header"><div class="avatar av-grey">AL</div><div><div class="csm-name">Andy Lim</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">ADP recording found &mdash; transcript pending at scan time, not counted</div></div>
    <div class="csm-card no-calls" data-csm="atisha"><div class="csm-card-header"><div class="avatar av-grey">AW</div><div><div class="csm-name">Atisha Waghela</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-csm="divyam"><div class="csm-card-header"><div class="avatar av-divyam">DD</div><div><div class="csm-name">Divyam Dewan</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Adobe &amp; BILL recordings found &mdash; Divyam not present in transcripts</div></div>
    <div class="csm-card no-calls" data-csm="varun"><div class="csm-card-header"><div class="avatar av-varun">VT</div><div><div class="csm-name">Varun Tiwari</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-csm="riley"><div class="csm-card-header"><div class="avatar av-riley">RR</div><div><div class="csm-name">Riley Rogers</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
  </div>`;
}

function dayCallsHTML_2026_05_01() {
  return `<div class="table-card"><table>
    <thead><tr><th>Time (PT)</th><th>CSM</th><th>Account</th><th>Duration</th><th>Signal</th></tr></thead>
    <tbody>
      <tr data-csm="nick" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 2:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">NJ</div>Nick Johnson</div></td><td><strong>Red Hat</strong> <span style="font-size:11px;color:#9ca3af">IT spend hierarchy &middot; AI agents roadmap &middot; IBM time series POC</span></td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="rani" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">RG</div>Rani Guy <span style="font-size:11px">(X-cov for PH)</span></div></td><td><strong>Cisco</strong> <span style="font-size:11px;color:#9ca3af">Install base + intent data &middot; market prediction model &middot; time series demo</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="rani" data-health="Concerning"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 4:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">RG</div>Rani Guy</div></td><td><strong>Hitachi Vantara</strong> <span style="font-size:11px;color:#9ca3af">QBR prep May 13 &middot; renewal timelines &middot; MCP expansion</span></td><td>30 min</td><td><span class="badge badge-concerning">&#128993; Concerning</span></td></tr>
      <tr data-csm="andy" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 1 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">AL</div>Andy Lim</div></td><td><strong>ADP</strong> <span style="font-size:11px;color:#9ca3af">Transcript pending at scan time &mdash; not counted</span></td><td>30 min</td><td><span class="badge" style="background:#fef3c7;color:#92400e">&#128336; Pending</span></td></tr>
    </tbody>
  </table></div>
  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-left:3px solid #3b82f6;border-radius:6px;padding:10px 14px;margin:10px 0;font-size:12px;color:#1e40af;">
    &#x2139;&#xfe0f; <strong>1 cross-coverage call</strong>: Rani Guy covered Cisco (3:00 PM) for Pam Huck. &nbsp;|&nbsp; <strong>1 pending transcript</strong>: ADP (Andy Lim, 3:00 PM) &mdash; still processing at scan time, not counted. &nbsp;|&nbsp; <strong>4 excluded</strong>: Adobe (TrustRadius team), BILL/Udemy (mis-attributed, external call), SAP Ariba/Fieldglass (TrustRadius team), SAP GEO Qs &amp; SAP SuccessFactors (no transcript).
  </div>
  <div class="empty-state" id="calls-empty" style="display:none"><div class="empty-icon">&#128269;</div>No calls match these filters.</div>`;
}

function dayPulsesHTML_2026_05_01() {
  const cards = [
    { csm:'nick',  health:'Healthy',    account:'Red Hat',          opp:'Vitally Pulse &mdash; May 1 Call',  arr:'Enterprise &middot; Nick Johnson',  excerpt:'IT spend hierarchy updates and data taxonomy alignment for wallet share project. AI agents roadmap discussion &mdash; HG data integration into AI pipelines. IBM time series POC progress reviewed. PO still in-flight; delivery cadence paused. Weflow rec: a76RN0000002Kp3YAE', csmlbl:'Nick Johnson', change:'New &middot; Pulse 24e82773' },
    { csm:'rani',  health:'Healthy',    account:'Cisco (WarRoom)',  opp:'Vitally Pulse &mdash; May 1 X-cov', arr:'Enterprise &middot; Rani Guy (covering Pam Huck)', excerpt:'X-cov for Pam Huck: Install base + intent data for Cisco&apos;s internal market prediction model. Buyer intent signal layering strategy. Time series data demo. API access requirements reviewed. Weflow rec: a76RN0000002Ey9YAE', csmlbl:'Rani Guy', change:'New &middot; Pulse 860082c1' },
    { csm:'rani',  health:'Concerning', account:'Hitachi Vantara',  opp:'Vitally Pulse &mdash; May 1 Call',  arr:'Enterprise &middot; Rani Guy',         excerpt:'QBR scheduled May 13 (Anders + Miguel). Renewal timeline alignment: intent Sep 28 &amp; install/spend Oct 22 &mdash; consolidation into single contract discussed. Phoenix/MCP expansion positioned. V3 intent migration progress reviewed. Weflow rec: a76RN0000002COTYA2', csmlbl:'Rani Guy', change:'New &middot; Pulse 164b69eb' },
  ];
  const bc = h => h==='Healthy'?'badge-healthy':'badge-concerning';
  const bi = h => h==='Healthy'?'&#128994;':'&#128993;';
  return `<div class="pulse-grid">${cards.map(c=>`
    <div class="pulse-card" data-csm="${c.csm}" data-health="${c.health}">
      <div class="pulse-card-top"><div><div class="pulse-account">${c.account}</div><div class="pulse-opp">${c.opp}</div><div class="pulse-arr">${c.arr}</div></div><span class="badge ${bc(c.health)}">${bi(c.health)} ${c.health}</span></div>
      <div class="pulse-excerpt">${c.excerpt}</div>
      <div class="pulse-footer"><span>${c.csmlbl}</span><span>${c.change}</span></div>
    </div>`).join('')}</div>
  <div class="empty-state" id="pulses-empty" style="display:none"><div class="empty-icon">&#128269;</div>No pulses match these filters.</div>`;
}

function dayActionsHTML_2026_05_01() {
  return `<div class="action-list">
    <div class="action-item ${doneActions.has(101)?'done':''}" data-csm="rani" id="action-101"><div class="action-checkbox ${doneActions.has(101)?'checked':''}" onclick="toggleAction(101)"></div><div class="action-body"><div class="action-title">&#x26a0;&#xfe0f; Hitachi Vantara QBR &mdash; May 13 with Anders + Miguel</div><div class="action-meta"><span class="urgency-badge urgency-high">TIME-SENSITIVE</span>Rani Guy &middot; QBR confirmed for May 13. Agenda should cover: renewal consolidation (intent Sep 28 + install Oct 22 into single contract), Phoenix/MCP expansion demo, V3 intent migration status. Ensure Anders (VP/decision-maker) is confirmed as attendee.</div></div></div>
    <div class="action-item ${doneActions.has(102)?'done':''}" data-csm="nick" id="action-102"><div class="action-checkbox ${doneActions.has(102)?'checked':''}" onclick="toggleAction(102)"></div><div class="action-body"><div class="action-title">&#x1F4CB; Red Hat PO follow-up &mdash; delivery cadence paused</div><div class="action-meta"><span class="urgency-badge urgency-medium">MEDIUM</span>Nick Johnson &middot; Data delivery paused pending PO clearance from Red Hat procurement. Chase Nick Dietsch on PO status. Note: IBM involvement in Red Hat renewal adds complexity. Maintain biweekly cadence while PO resolves.</div></div></div>
    <div class="action-item ${doneActions.has(103)?'done':''}" data-csm="andy" id="action-103"><div class="action-checkbox ${doneActions.has(103)?'checked':''}" onclick="toggleAction(103)"></div><div class="action-body"><div class="action-title">&#x23F3; ADP transcript pending &mdash; Andy Lim</div><div class="action-meta"><span class="urgency-badge urgency-low">FOLLOW-UP</span>Andy Lim &middot; ADP recording (May 1, 3:00 PM, 30 min) had no transcript at scan time. Check Weflow rec a76RN0000002KInYAM once transcript is available. Create Vitally note and count call if Andy confirmed as speaker.</div></div></div>
  </div>
  <div class="empty-state" id="actions-empty" style="display:none"><div class="empty-icon">&#128269;</div>No action items match these filters.</div>`;
}

// ─── MAY 4, 2026 ───────────────────────────────────────────────

function dayData_2026_05_04() {
  return {
    calls: [
      { ts: 'May 4 · 6:30 AM',  csm: 'atisha', account: 'TD Synnex',  note: 'Customer T831833V flagged 44K credits consumed vs 11K expected · Atisha escalating', mins: 30, health: 'Concerning' },
      { ts: 'May 4 · 8:30 AM',  csm: 'divyam', account: 'Blackbaud',  note: 'Cadence call · usage and adoption check-in', mins: 30, health: 'Healthy' },
      { ts: 'May 4 · 11:00 AM', csm: 'divyam', account: 'Quadient',   note: 'IDL renewal cadence · success plan progress', mins: 30, health: 'Healthy' },
      { ts: 'May 4 · 11:30 AM', csm: 'divyam', account: 'OpenAI',     note: 'Cadence call · data usage and expansion discussion', mins: 30, health: 'Healthy' },
      { ts: 'May 4 · 10:00 AM', csm: 'riley',  account: 'Red Hat',    note: 'TR IDL program session · Riley running TR IDL on Nick\'s account', mins: 30, health: 'Healthy', xcov: 'nick' },
    ],
    pulses: [
      { csm: 'atisha', account: 'TD Synnex',  health: 'Concerning', note: 'Customer T831833V flagged unexpected credit consumption: 44K credits used vs 11K expected. Atisha escalating internally. Root cause investigation in progress.' },
      { csm: 'divyam', account: 'Blackbaud',  health: 'Healthy',    note: 'Cadence call completed. Usage and adoption check-in. Account in good standing.' },
      { csm: 'divyam', account: 'Quadient',   health: 'Healthy',    note: 'IDL renewal cadence call. Success plan progress reviewed. Account healthy.' },
      { csm: 'divyam', account: 'OpenAI',     health: 'Healthy',    note: 'Cadence call. Data usage and expansion discussed. Account healthy.' },
      { csm: 'riley',  account: 'Red Hat',    health: 'Healthy',    note: 'Cross-coverage: Riley Rogers ran TR IDL program session on Nick Johnson\'s Red Hat account. IDL engagement healthy.' },
    ],
  };
}

function dayMeta_2026_05_04() {
  return {
    pills: [['dot-teal','5 Qualifying Calls'],['dot-green','5 Vitally Pulses'],['dot-amber','1 Cross-Coverage'],['dot-red','1 Concerning']],
    tabs:  ['Overview','Calls (5)','Pulses (5)','Action Items (3)'],
  };
}

function dayOverviewHTML_2026_05_04() {
  return `<div class="section-label">Team Activity &mdash; Monday May 4, 2026</div>
  <div class="overview-grid">
    <div class="csm-card has-calls" data-csm="atisha"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-grey">AW</div><div><div class="csm-name">Atisha Waghela</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-red">1</div><div class="metric-lbl">Concerning</div></div><div><div class="metric-num m-grey">30m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">TD Synnex &middot; Customer flagged unexpected credit consumption &middot; 44K used vs 11K expected &middot; escalating</div></div>
    <div class="csm-card has-calls" data-csm="divyam"><span class="call-badge">3 CALLS</span><div class="csm-card-header"><div class="avatar av-divyam">DD</div><div><div class="csm-name">Divyam Dewan</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">3</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">3</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">90m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Blackbaud &middot; Quadient &middot; OpenAI &mdash; all Healthy</div></div>
    <div class="csm-card has-calls" data-csm="riley"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-riley">RR</div><div><div class="csm-name">Riley Rogers</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Pulses</div></div><div><div class="metric-num m-grey">30m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Red Hat (X-cov for Nick Johnson) &middot; TR IDL program session &middot; Healthy</div></div>
    <div class="csm-card no-calls" data-csm="nick"><div class="csm-card-header"><div class="avatar av-grey">NJ</div><div><div class="csm-name">Nick Johnson</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Red Hat covered by Riley Rogers on May 4</div></div>
    <div class="csm-card no-calls" data-csm="rani"><div class="csm-card-header"><div class="avatar av-grey">RG</div><div><div class="csm-name">Rani Guy</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Docusign recording found &mdash; Rani not a speaker (Ziad Amira + Rishabh Wadhwa)</div></div>
    <div class="csm-card no-calls" data-csm="varun"><div class="csm-card-header"><div class="avatar av-varun">VT</div><div><div class="csm-name">Varun Tiwari</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Open Text recording found &mdash; no transcript available, unable to verify</div></div>
    <div class="csm-card no-calls" data-csm="pam"><div class="csm-card-header"><div class="avatar av-grey">PH</div><div><div class="csm-name">Pam Huck</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-csm="andy"><div class="csm-card-header"><div class="avatar av-grey">AL</div><div><div class="csm-name">Andy Lim</div><div class="csm-role">Enterprise CSM</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">Intuit recording found &mdash; Atisha not a speaker (sales/SE call)</div></div>
  </div>`;
}

function dayCallsHTML_2026_05_04() {
  return `<div class="table-card"><table>
    <thead><tr><th>Time (PT)</th><th>CSM</th><th>Account</th><th>Duration</th><th>Signal</th></tr></thead>
    <tbody>
      <tr data-csm="atisha" data-health="Concerning"><td style="color:#9ca3af;font-size:12px">May 4 &middot; 6:30 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">AW</div>Atisha Waghela</div></td><td><strong>TD Synnex</strong> <span style="font-size:11px;color:#9ca3af">Customer T831833V flagged 44K credits consumed vs 11K expected &middot; Atisha escalating</span></td><td>30 min</td><td><span class="badge badge-concerning">&#128993; Concerning</span></td></tr>
      <tr data-csm="divyam" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 4 &middot; 8:30 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-divyam">DD</div>Divyam Dewan</div></td><td><strong>Blackbaud</strong> <span style="font-size:11px;color:#9ca3af">Cadence call &middot; usage and adoption check-in</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="divyam" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 4 &middot; 11:00 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-divyam">DD</div>Divyam Dewan</div></td><td><strong>Quadient</strong> <span style="font-size:11px;color:#9ca3af">IDL renewal cadence &middot; success plan progress</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="divyam" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 4 &middot; 11:30 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-divyam">DD</div>Divyam Dewan</div></td><td><strong>OpenAI</strong> <span style="font-size:11px;color:#9ca3af">Cadence call &middot; data usage and expansion discussion</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-csm="riley" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 4 &middot; 10:00 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-riley">RR</div>Riley Rogers <span style="font-size:11px">(X-cov for NJ)</span></div></td><td><strong>Red Hat</strong> <span style="font-size:11px;color:#9ca3af">TR IDL program session &middot; Riley running TR IDL on Nick&apos;s account</span></td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
    </tbody>
  </table></div>
  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-left:3px solid #3b82f6;border-radius:6px;padding:10px 14px;margin:10px 0;font-size:12px;color:#1e40af;">
    &#x2139;&#xfe0f; <strong>1 cross-coverage call</strong>: Riley Rogers covered Red Hat (10:00 AM) for Nick Johnson (TR IDL session). &nbsp;|&nbsp; <strong>3 excluded</strong>: Intuit (CSM Atisha not a speaker &mdash; sales/SE call), Docusign (Rani Guy not a speaker &mdash; Ziad Amira + Rishabh Wadhwa), Open Text (has_transcript: false &mdash; unable to verify Varun Tiwari).
  </div>
  <div class="empty-state" id="calls-empty" style="display:none"><div class="empty-icon">&#128269;</div>No calls match these filters.</div>`;
}

function dayPulsesHTML_2026_05_04() {
  const cards = [
    { csm:'atisha', health:'Concerning', account:'TD Synnex',  opp:'Vitally Pulse &mdash; May 4 Call',  arr:'Enterprise &middot; Atisha Waghela',  excerpt:'Customer T831833V flagged unexpected credit consumption: 44K credits used vs 11K expected. Atisha escalating internally. Root cause investigation in progress. Weflow rec: a76RN0000002N29YAE', csmlbl:'Atisha Waghela', change:'New &middot; Pulse e2e0fc99' },
    { csm:'divyam', health:'Healthy',    account:'Blackbaud',  opp:'Vitally Pulse &mdash; May 4 Call',  arr:'Enterprise &middot; Divyam Dewan',      excerpt:'Cadence call completed. Usage and adoption check-in. Account in good standing. Weflow rec: a76RN0000002MvhYAE', csmlbl:'Divyam Dewan', change:'Existing Pulse' },
    { csm:'divyam', health:'Healthy',    account:'Quadient',   opp:'Vitally Pulse &mdash; May 4 Call',  arr:'Enterprise &middot; Divyam Dewan',      excerpt:'IDL renewal cadence call. Success plan progress reviewed. Account healthy. Weflow rec: a76RN0000002LRlYAM', csmlbl:'Divyam Dewan', change:'Existing Pulse' },
    { csm:'divyam', health:'Healthy',    account:'OpenAI',     opp:'Vitally Pulse &mdash; May 4 Call',  arr:'Enterprise &middot; Divyam Dewan',      excerpt:'Cadence call. Data usage and expansion discussed. Account healthy. Weflow rec: a76RN0000002HmMYAU', csmlbl:'Divyam Dewan', change:'Existing Pulse' },
    { csm:'riley',  health:'Healthy',    account:'Red Hat',    opp:'Vitally Pulse &mdash; May 4 X-cov', arr:'Enterprise &middot; Riley Rogers (covering Nick Johnson)', excerpt:'Cross-coverage: Riley Rogers ran TR IDL program session on Nick Johnson&apos;s Red Hat account. IDL engagement healthy. Weflow rec: a76RN0000002EoTYAU', csmlbl:'Riley Rogers', change:'New &middot; Pulse 83ae0251' },
  ];
  const bc = h => h==='Healthy'?'badge-healthy':'badge-concerning';
  const bi = h => h==='Healthy'?'&#128994;':'&#128993;';
  return `<div class="pulse-grid">${cards.map(c=>`
    <div class="pulse-card" data-csm="${c.csm}" data-health="${c.health}">
      <div class="pulse-card-top"><div><div class="pulse-account">${c.account}</div><div class="pulse-opp">${c.opp}</div><div class="pulse-arr">${c.arr}</div></div><span class="badge ${bc(c.health)}">${bi(c.health)} ${c.health}</span></div>
      <div class="pulse-excerpt">${c.excerpt}</div>
      <div class="pulse-footer"><span>${c.csmlbl}</span><span>${c.change}</span></div>
    </div>`).join('')}</div>
  <div class="empty-state" id="pulses-empty" style="display:none"><div class="empty-icon">&#128269;</div>No pulses match these filters.</div>`;
}

function dayActionsHTML_2026_05_04() {
  return `<div class="action-list">
    <div class="action-item ${doneActions.has(401)?'done':''}" data-csm="atisha" id="action-401"><div class="action-checkbox ${doneActions.has(401)?'checked':''}" onclick="toggleAction(401)"></div><div class="action-body"><div class="action-title">&#x26a0;&#xfe0f; TD Synnex &mdash; Credit consumption anomaly &middot; customer T831833V</div><div class="action-meta"><span class="urgency-badge urgency-high">HIGH PRIORITY</span>Atisha Waghela &middot; Customer reported 44K credits consumed vs 11K expected. Atisha is escalating internally. Identify root cause (over-querying, misconfiguration, or billing error), communicate findings to customer, and resolve or credit. Time-sensitive for retention risk.</div></div></div>
    <div class="action-item ${doneActions.has(402)?'done':''}" data-csm="varun" id="action-402"><div class="action-checkbox ${doneActions.has(402)?'checked':''}" onclick="toggleAction(402)"></div><div class="action-body"><div class="action-title">&#x23F3; Open Text transcript pending &mdash; Varun Tiwari</div><div class="action-meta"><span class="urgency-badge urgency-medium">FOLLOW-UP</span>Varun Tiwari &middot; Open Text recording (May 4, Weflow rec: a76RN0000002MndYAE) had has_transcript: false at scan time. Once transcript is available, verify Varun as active speaker and create Vitally pulse. "HGI + Open Text : Bi-Weekly Cadence" recording.</div></div></div>
    <div class="action-item ${doneActions.has(403)?'done':''}" data-csm="riley" id="action-403"><div class="action-checkbox ${doneActions.has(403)?'checked':''}" onclick="toggleAction(403)"></div><div class="action-body"><div class="action-title">&#x1F4CB; Red Hat cross-coverage &mdash; sync with Nick Johnson</div><div class="action-meta"><span class="urgency-badge urgency-low">LOW</span>Riley Rogers covered Red Hat TR IDL session for Nick Johnson on May 4. Ensure Nick is aware of session outcomes and any follow-ups. Riley&apos;s pulse (83ae0251) logged with cross-coverage context.</div></div></div>
  </div>
  <div class="empty-state" id="actions-empty" style="display:none"><div class="empty-icon">&#128269;</div>No action items match these filters.</div>`;
}
