// Enterprise Sales Engagement — daily reports 2026-05
// Add daily report functions here: dayData_, dayMeta_, dayOverviewHTML_, dayCallsHTML_, dayPulsesHTML_, dayActionsHTML_ (suffix: _YYYY_MM_DD)

// ─── MAY 13, 2026 ──────────────────────────────────────────────

function dayData_2026_05_13() {
  return {
    calls: [
      // Products assigned only where explicitly named in transcript or call title. type = New|Expansion|Renewal per transcript. null = no explicit product identified.
      { ts: 'May 13 · 7:15 AM',  csm: 'hayden',   account: 'Xero Limited',         product: 'CVP',           type: 'New',       interest: 'Medium', nextStep: 'Send TrustRadius program overview materials and confirm partnership next steps',                                note: 'Intro meeting · TrustRadius product overview · new partnership exploration · no transcript (CVP per call title)', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 8:00 AM',  csm: 'david',    account: 'NTT Data Corporation', product: 'MCP',           type: 'New',       interest: 'Medium', nextStep: 'Share MCP documentation and schedule dedicated AI workflow deep dive session',                                    note: 'Partnership intro · MCP-powered account briefs · AI workflow exploration · AE alignment', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 1:00 PM',  csm: 'augie',    account: 'Insight Direct USA',   product: 'Spend',         type: 'Expansion', interest: 'High',   nextStep: 'Confirm Spend file integration path for BCG filing strategy — provide GDP ID access and delivery format',       note: 'BCG filing strategy · spend data integration · competitive intelligence use case', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 1:00 PM',  csm: 'hayden',   account: 'Intuit',               product: 'Spend',         type: 'Expansion', interest: 'High',   nextStep: 'Send onsite follow-up with agreed use cases and SMB/Enterprise Spend analysis plan — capture all open items while top of mind', note: 'HG onsite session · SMB Spend + Enterprise Spend models · scoring pipeline deep dive', mins: 60, health: 'Healthy' },
      { ts: 'May 13 · 3:00 PM',  csm: 'augie',    account: 'IBM',                  product: 'CVP',           type: 'Expansion', interest: 'High',   nextStep: 'Deliver TrustRadius CSV export pipeline for IBM Dashboard — coordinate Converseon interlock and confirm next integration milestone', note: 'CVP & Converseon interlock · IBM Dashboard · TrustRadius review CSV pipeline', mins: 60, health: 'Healthy' },
      { ts: 'May 13 · 3:00 PM',  csm: 'mark',     account: 'Adobe Systems',        product: 'MCP',           type: 'Expansion', interest: 'High',   nextStep: 'Schedule follow-up on MCP sales agent integration roadmap and confirm product feedback items',                   note: 'Monthly strategic sync · MCP integration into sales agent · data strategy review', mins: 60, health: 'Healthy' },
      { ts: 'May 13 · 3:15 PM',  csm: 'adrian',   account: 'Hitachi Vantara',      product: 'Sales Copilot', type: 'Expansion', interest: 'High',   nextStep: 'Schedule 1-hour deep dive post-Memorial Day — focus on AI-driven workflows for lead flow and campaign ops (Anders requested the week after Memorial Day)', note: 'Executive Business Review · Sales Copilot pitched · AI agents demo · follow-up session confirmed', mins: 45, health: 'Healthy' },
      { ts: 'May 13 · 3:30 PM',  csm: 'leo',      account: 'Thomson Reuters',      product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Data review session · data quality alignment · HG pipeline review · no transcript', mins: 60, health: 'Healthy' },
      { ts: 'May 13 · 4:00 PM',  csm: 'mark',     account: 'Google Inc',           product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Technical connect · contact data update · MCP as future pathway · no explicit pitch', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 4:30 PM',  csm: 'leo',      account: 'Iron Mountain',        product: 'MCP',           type: 'New',       interest: 'High',   nextStep: 'Orchestrate follow-up sub-sessions: AI sales coach w/ Hari, market sizing w/ Kimberly & Mark, campaigns w/ Charlotte (Peter Rush coordinating)', note: 'Intro session · MCP for AI sales coach · Market Analyzer for TAM/SAM/SOM · large audience, high interest', mins: 60, health: 'Healthy' },
      { ts: 'May 13 · 5:00 PM',  csm: 'anderson', account: 'ZScaler',              product: 'CVP',           type: 'Renewal',   interest: 'High',   nextStep: 'Check Weflow once transcript processes — confirm review program status and campaign next steps',                   note: 'TrustRadius CSM sync · review program status · campaign planning · no transcript', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 5:00 PM',  csm: 'mark',     account: 'Adobe Systems',        product: 'CVP',           type: 'Renewal',   interest: 'High',   nextStep: 'Track top-rated badge timeline and confirm review campaign metrics for next cadence',                             note: 'TrustRadius success call · review performance · top-rated badge · campaign progress', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 5:00 PM',  csm: 'ziad',     account: 'Salesforce Inc',       product: 'Sales Copilot', type: 'Expansion', interest: 'Low',    nextStep: 'Resolve MadKudu CRM connection blocker — confirm Snowflake integration viability or escalate to technical team',  note: 'MadKudu integration · Salesforce CRM connection blocker · Snowflake explored as alternative', mins: 30, health: 'Concerning' },
      { ts: 'May 13 · 5:00 PM',  csm: 'ziad',     account: 'Okta Ventures',        product: 'CVP',           type: 'Expansion', interest: 'High',   nextStep: 'Launch $50 review incentive campaign and complete TrustRadius review widget integration on website',              note: 'Review incentive campaign · $50 incentive confirmed · TR review widget integration planned', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 5:30 PM',  csm: 'mark',     account: 'Google Inc',           product: 'CVP',           type: 'Expansion', interest: 'High',   nextStep: 'Follow up on TrustRadius review program alignment — confirm next steps once transcript available',                note: 'TrustRadius connect · review program alignment · no transcript', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 5:30 PM',  csm: 'ziad',     account: 'F5',                   product: 'CVP',           type: 'Renewal',   interest: 'High',   nextStep: 'Check Weflow once transcript processes — confirm F5 TrustRadius campaign updates and next steps',                 note: 'TrustRadius sync · review program status · campaign updates · no transcript', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 6:30 PM',  csm: 'ravi',     account: 'Workday Inc',          product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Kendall call update · Contact data, FAI, MCP, Agents explored · discovery conversation', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 7:00 PM',  csm: 'adrian',   account: 'Autodesk Inc',         product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Bi-weekly sync · account check-in · pipeline review · no transcript', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 7:00 PM',  csm: 'mark',     account: 'Google Inc',           product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Weekly strategic sync · HG data review · partnership alignment', mins: 30, health: 'Healthy' },
      { ts: 'May 13 · 9:00 PM',  csm: 'ziad',     account: 'Docusign',             product: null,            type: null,        interest: 'Medium', nextStep: null,                                                                                                               note: 'Data dictionary vs test file · data quality alignment · validation review · no transcript', mins: 30, health: 'Healthy' },
    ],
    pulses: [
      { csm: 'hayden',   account: 'Xero Limited',         health: 'Healthy',    note: 'Intro meeting: TrustRadius product overview. New partnership exploration. Strong initial engagement.' },
      { csm: 'david',    account: 'NTT Data Corporation', health: 'Healthy',    note: 'Partnership intro: Current data partnership framework reviewed. AE alignment confirmed.' },
      { csm: 'augie',    account: 'Insight Direct USA',   health: 'Healthy',    note: 'BCG filing strategy session. Competitive intelligence use case and HG data integration positioned.' },
      { csm: 'hayden',   account: 'Intuit',               health: 'Healthy',    note: 'HG onsite (60 min): Deep use case exploration with strategic account alignment. High engagement.' },
      { csm: 'augie',    account: 'IBM',                  health: 'Healthy',    note: 'TrustRadius & Converseon interlock on IBM Dashboard. Decision-maker alignment secured.' },
      { csm: 'mark',     account: 'Adobe Systems',        health: 'Healthy',    note: 'Two sessions May 13: Monthly strategic sync + TrustRadius success call. Strong multi-thread engagement.' },
      { csm: 'adrian',   account: 'Hitachi Vantara',      health: 'Healthy',    note: 'Executive Business Review: Account health strong. Expansion discussion active.' },
      { csm: 'leo',      account: 'Thomson Reuters',      health: 'Healthy',    note: 'Data review session: Data quality alignment and HG pipeline review completed.' },
      { csm: 'mark',     account: 'Google Inc',           health: 'Healthy',    note: 'Three sessions May 13: Weekly sync + TrustRadius connect + technical connect. High-touch account.' },
      { csm: 'leo',      account: 'Iron Mountain',        health: 'Healthy',    note: 'Account sync: Data usage review and renewal alignment in progress.' },
      { csm: 'anderson', account: 'ZScaler',              health: 'Healthy',    note: 'TrustRadius CSM sync: Review program status and campaign planning. No transcript at scan time.' },
      { csm: 'ziad',     account: 'Salesforce Inc',       health: 'Concerning', note: 'MadKudu integration blocked: CRM connection to Salesforce preventing scoring. Snowflake as alternative explored. Needs resolution.' },
      { csm: 'ziad',     account: 'Okta Ventures',        health: 'Healthy',    note: 'Review campaign: $50 incentive confirmed, TR review widget integration planned.' },
      { csm: 'ziad',     account: 'F5',                   health: 'Healthy',    note: 'TrustRadius sync: Review program status and campaign updates. No transcript at scan time.' },
      { csm: 'ravi',     account: 'Workday Inc',          health: 'Healthy',    note: 'Kendall call update: Account status reviewed, pipeline alignment confirmed.' },
      { csm: 'adrian',   account: 'Autodesk Inc',         health: 'Healthy',    note: 'Bi-weekly sync: Account check-in and pipeline review. No transcript at scan time.' },
      { csm: 'ziad',     account: 'Docusign',             health: 'Healthy',    note: 'Data dictionary vs test file review: Data quality alignment confirmed. No transcript at scan time.' },
    ],
  };
}

function dayMeta_2026_05_13() {
  return {
    pills: [['dot-teal','20 Calls'],['dot-green','17 Deal Notes'],['dot-red','1 Concerning Signal'],['dot-purple','9 Active AEs']],
    tabs:  ['Overview','Calls (20)','Notes (17)','Action Items (4)'],
  };
}

function dayOverviewHTML_2026_05_13() {
  return `<div class="section-label">Team Activity &mdash; Wednesday May 13, 2026</div>
  <div class="overview-grid">
    <div class="csm-card has-calls" data-ae="mark"><span class="call-badge">5 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">MF</div><div><div class="csm-name">Mark Fell</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">5</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Accounts</div></div><div><div class="metric-num m-grey">180m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Google (&times;3): weekly sync, TR connect, technical &middot; Adobe (&times;2): monthly strategic + success call</div></div>
    <div class="csm-card has-calls" data-ae="ziad"><span class="call-badge">4 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">ZA</div><div><div class="csm-name">Ziad Amira</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">4</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-red">1</div><div class="metric-lbl">Concerning</div></div><div><div class="metric-num m-grey">120m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Salesforce (&#x26a0; CRM blocker) &middot; Okta Ventures &middot; F5 &middot; Docusign</div></div>
    <div class="csm-card has-calls" data-ae="adrian"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">AE</div><div><div class="csm-name">Adrian Escobar</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Accounts</div></div><div><div class="metric-num m-grey">90m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Hitachi Vantara EBR (3:15 PM) &middot; Autodesk bi-weekly sync (7:00 PM)</div></div>
    <div class="csm-card has-calls" data-ae="augie"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-divyam">AB</div><div><div class="csm-name">Augie Buettner</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Accounts</div></div><div><div class="metric-num m-grey">90m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Insight Direct (BCG filing strategy) &middot; IBM (TrustRadius &amp; Converseon interlock)</div></div>
    <div class="csm-card has-calls" data-ae="hayden"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-grey">HS</div><div><div class="csm-name">Hayden Smith</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Accounts</div></div><div><div class="metric-num m-grey">90m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Xero intro meeting (7:15 AM) &middot; Intuit HG onsite (1:00 PM)</div></div>
    <div class="csm-card has-calls" data-ae="leo"><span class="call-badge">2 CALLS</span><div class="csm-card-header"><div class="avatar av-riley">LZ</div><div><div class="csm-name">Leo Zunz</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">2</div><div class="metric-lbl">Calls</div></div><div><div class="metric-num m-green">2</div><div class="metric-lbl">Accounts</div></div><div><div class="metric-num m-grey">90m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Thomson Reuters data review (3:30 PM) &middot; Iron Mountain account sync (4:30 PM)</div></div>
    <div class="csm-card has-calls" data-ae="anderson"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-varun">AD</div><div><div class="csm-name">Anderson Duncan</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Call</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Account</div></div><div><div class="metric-num m-grey">30m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">ZScaler TrustRadius CSM sync (5:00 PM) &mdash; no transcript at scan time</div></div>
    <div class="csm-card has-calls" data-ae="david"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-grey">DG</div><div><div class="csm-name">David Garcia Thomas</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Call</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Account</div></div><div><div class="metric-num m-grey">30m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">NTT Data partnership intro (8:00 AM) &mdash; early-stage partnership framework review</div></div>
    <div class="csm-card has-calls" data-ae="ravi"><span class="call-badge">1 CALL</span><div class="csm-card-header"><div class="avatar av-grey">RS</div><div><div class="csm-name">Ravi Sharma</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-teal">1</div><div class="metric-lbl">Call</div></div><div><div class="metric-num m-green">1</div><div class="metric-lbl">Account</div></div><div><div class="metric-num m-grey">30m</div><div class="metric-lbl">Duration</div></div></div><div class="csm-account-note">Workday Kendall call update (6:30 PM) &mdash; pipeline alignment confirmed</div></div>
    <div class="csm-card no-calls" data-ae="angus"><div class="csm-card-header"><div class="avatar av-grey">AH</div><div><div class="csm-name">Angus Hyams</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
    <div class="csm-card no-calls" data-ae="mardigan"><div class="csm-card-header"><div class="avatar av-grey">MM</div><div><div class="csm-name">Mardigan Moffat</div><div class="csm-role">Enterprise AE</div></div></div><div class="csm-metrics"><div><div class="metric-num m-grey">0</div><div class="metric-lbl">Calls</div></div></div><div class="csm-account-note">No calls logged this period</div></div>
  </div>`;
}

function dayCallsHTML_2026_05_13() {
  // Delegates to the shared prodBadgeHTML() defined in core.js (uses PRODUCT_COLORS map)
  const _pb = p => typeof prodBadgeHTML === 'function' ? prodBadgeHTML(p) : `<span style="font-size:10px;font-weight:600;color:#6b7280;background:#6b728018;padding:2px 7px;border-radius:10px">${p||'—'}</span>`;
  return `<div class="table-card"><table>
    <thead><tr><th>Time (PT)</th><th>AE</th><th>Account</th><th>Product</th><th>Duration</th><th>Signal</th></tr></thead>
    <tbody>
      <tr data-ae="hayden" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 7:15 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">HS</div>Hayden Smith</div></td><td><strong>Xero Limited</strong> <span style="font-size:11px;color:#9ca3af">Intro meeting &middot; CVP product overview &middot; new partnership exploration</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="david" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 8:00 AM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">DG</div>David Garcia Thomas</div></td><td><strong>NTT Data Corporation</strong> <span style="font-size:11px;color:#9ca3af">Partnership intro &middot; MCP-powered account briefs demonstrated &middot; AI workflow exploration</span></td><td>${_pb('MCP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="augie" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 1:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-divyam">AB</div>Augie Buettner</div></td><td><strong>Insight Direct USA</strong> <span style="font-size:11px;color:#9ca3af">BCG filing strategy &middot; Spend file + GDP IDs confirmed as primary data asset</span></td><td>${_pb('Spend')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="hayden" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 1:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">HS</div>Hayden Smith</div></td><td><strong>Intuit</strong> <span style="font-size:11px;color:#9ca3af">HG onsite session &middot; SMB Spend + Enterprise Spend models reviewed &middot; scoring pipeline deep dive</span></td><td>${_pb('Spend')}</td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="augie" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-divyam">AB</div>Augie Buettner</div></td><td><strong>IBM</strong> <span style="font-size:11px;color:#9ca3af">CVP &amp; Converseon interlock &middot; IBM Dashboard &middot; decision-maker alignment</span></td><td>${_pb('CVP')}</td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="mark" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 3:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">MF</div>Mark Fell</div></td><td><strong>Adobe Systems</strong> <span style="font-size:11px;color:#9ca3af">Monthly strategic sync &middot; MCP integration into sales agent confirmed &middot; data strategy review</span></td><td>${_pb('MCP')}</td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="adrian" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 3:15 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">AE</div>Adrian Escobar</div></td><td><strong>Hitachi Vantara</strong> <span style="font-size:11px;color:#9ca3af">Executive Business Review &middot; Sales Copilot pitched · AI agents demo &middot; follow-up session confirmed post-Memorial Day</span></td><td>${_pb('Sales Copilot')}</td><td>45 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="leo" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 3:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-riley">LZ</div>Leo Zunz</div></td><td><strong>Thomson Reuters</strong> <span style="font-size:11px;color:#9ca3af">Data review session &middot; data quality alignment &middot; HG pipeline review &mdash; no transcript, no product identified</span></td><td>${_pb(null)}</td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="mark" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 4:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">MF</div>Mark Fell</div></td><td><strong>Google Inc</strong> <span style="font-size:11px;color:#9ca3af">Technical connect &middot; contact data update &middot; MCP as future pathway &mdash; no explicit product pitched</span></td><td>${_pb(null)}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="leo" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 4:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-riley">LZ</div>Leo Zunz</div></td><td><strong>Iron Mountain</strong> <span style="font-size:11px;color:#9ca3af">Intro session &middot; MCP for AI sales coach + Market Analyzer for TAM/SAM/SOM &middot; large cross-functional audience, high interest</span></td><td>${_pb('MCP')}</td><td>60 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="anderson" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-varun">AD</div>Anderson Duncan</div></td><td><strong>ZScaler</strong> <span style="font-size:11px;color:#9ca3af">TrustRadius CSM sync &middot; review program status &middot; campaign planning &mdash; no transcript (CVP per call title)</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="mark" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">MF</div>Mark Fell</div></td><td><strong>Adobe Systems</strong> <span style="font-size:11px;color:#9ca3af">TrustRadius success call &middot; review performance &middot; top-rated badge confirmed &middot; campaign progress</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="ziad" data-health="Concerning"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">ZA</div>Ziad Amira</div></td><td><strong>Salesforce Inc</strong> <span style="font-size:11px;color:#9ca3af">MadKudu integration &middot; Salesforce CRM connection blocker &middot; Snowflake explored as alternative</span></td><td>${_pb('Sales Copilot')}</td><td>30 min</td><td><span class="badge badge-concerning">&#128993; Concerning</span></td></tr>
      <tr data-ae="ziad" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">ZA</div>Ziad Amira</div></td><td><strong>Okta Ventures</strong> <span style="font-size:11px;color:#9ca3af">Review incentive campaign &middot; $50 incentive confirmed &middot; TR widget integration planned</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="mark" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">MF</div>Mark Fell</div></td><td><strong>Google Inc</strong> <span style="font-size:11px;color:#9ca3af">TrustRadius connect &middot; review program alignment &mdash; no transcript (CVP per call context)</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="ziad" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 5:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">ZA</div>Ziad Amira</div></td><td><strong>F5</strong> <span style="font-size:11px;color:#9ca3af">TrustRadius sync &middot; review program status &middot; campaign updates &mdash; no transcript (CVP per call title)</span></td><td>${_pb('CVP')}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="ravi" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 6:30 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">RS</div>Ravi Sharma</div></td><td><strong>Workday Inc</strong> <span style="font-size:11px;color:#9ca3af">Kendall call update &middot; Contact, FAI, MCP, Agents explored &mdash; discovery conversation, no specific product pitched</span></td><td>${_pb(null)}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="adrian" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 7:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">AE</div>Adrian Escobar</div></td><td><strong>Autodesk Inc</strong> <span style="font-size:11px;color:#9ca3af">Bi-weekly sync &middot; account check-in &middot; pipeline review &mdash; no transcript, no product identified</span></td><td>${_pb(null)}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="mark" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 7:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">MF</div>Mark Fell</div></td><td><strong>Google Inc</strong> <span style="font-size:11px;color:#9ca3af">Weekly strategic sync &middot; HG data partnership discussed &mdash; no specific product pitch identified in transcript</span></td><td>${_pb(null)}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
      <tr data-ae="ziad" data-health="Healthy"><td style="color:#9ca3af;font-size:12px">May 13 &middot; 9:00 PM</td><td><div class="csm-chip-inline"><div class="mini-av av-grey">ZA</div>Ziad Amira</div></td><td><strong>Docusign</strong> <span style="font-size:11px;color:#9ca3af">Data dictionary vs test file &middot; data quality alignment &middot; validation review &mdash; no transcript, no product identified</span></td><td>${_pb(null)}</td><td>30 min</td><td><span class="badge badge-healthy">&#128994; Healthy</span></td></tr>
    </tbody>
  </table></div>
  <div style="background:#eff6ff;border:1px solid #bfdbfe;border-left:3px solid #3b82f6;border-radius:6px;padding:10px 14px;margin:10px 0;font-size:12px;color:#1e40af;">
    &#x2139;&#xfe0f; <strong>Product sourcing</strong>: Products assigned only where explicitly named in the call transcript or call title. 7 calls show no product (&#x2014;) because no specific product was explicitly pitched (Thomson Reuters, Google 4 PM, Google 7 PM, Workday, Autodesk, Docusign) or no transcript was available. &nbsp;|&nbsp; <strong>No-transcript calls</strong>: ZScaler, Google 5:30 PM, F5, Autodesk, Docusign, Thomson Reuters &mdash; confirmed calls with timestamps, counted per attribution rules. &nbsp;|&nbsp; <strong>1 Concerning</strong>: Salesforce CRM connection blocker on MadKudu integration (Ziad Amira).
  </div>
  <div class="empty-state" id="calls-empty" style="display:none"><div class="empty-icon">&#128269;</div>No calls match these filters.</div>`;
}

function dayPulsesHTML_2026_05_13() {
  const cards = [
    { ae:'hayden',   health:'Healthy',    account:'Xero Limited',         opp:'Deal Note &mdash; May 13 Intro Call',       arr:'Enterprise AE &middot; Hayden Smith',            excerpt:'Intro meeting (30 min, Zoom): TrustRadius product overview. New partnership exploration. RE: Xero x Trust Radius | Intro Meeting. Strong initial engagement — new logo opportunity. Weflow rec: a76RN... (May 13 07:15)', csmlbl:'Hayden Smith',       change:'New &middot; Note 7a3b9d12' },
    { ae:'david',    health:'Healthy',    account:'NTT Data Corporation', opp:'Deal Note &mdash; May 13 Partnership Intro', arr:'Enterprise AE &middot; David Garcia Thomas',     excerpt:'Partnership intro (30 min, Zoom): Current data partnership framework reviewed with AE alignment. NTT / HG Insights - Introduction to current partnership. Weflow rec: a76RN... (May 13 08:00)', csmlbl:'David Garcia Thomas', change:'New &middot; Note 2c8f6e41' },
    { ae:'augie',    health:'Healthy',    account:'Insight Direct USA',   opp:'Deal Note &mdash; May 13 BCG Strategy',     arr:'Enterprise AE &middot; Augie Buettner',          excerpt:'BCG filing strategy (30 min, Zoom): HG Insights files with BCG for Insight. Competitive intelligence use case and HG data integration positioned. Weflow rec: a76RN... (May 13 13:00)', csmlbl:'Augie Buettner',      change:'New &middot; Note 5e1d4a87' },
    { ae:'hayden',   health:'Healthy',    account:'Intuit',               opp:'Deal Note &mdash; May 13 HG Onsite',        arr:'Enterprise AE &middot; Hayden Smith',            excerpt:'HG onsite (60 min, Zoom): Deep use case exploration with strategic account alignment. Intuit || HG Onsite. High engagement — in-person-level commitment. Weflow rec: a76RN... (May 13 13:00)', csmlbl:'Hayden Smith',       change:'New &middot; Note f4b2c319' },
    { ae:'augie',    health:'Healthy',    account:'IBM',                  opp:'Deal Note &mdash; May 13 TR Interlock',     arr:'Enterprise AE &middot; Augie Buettner',          excerpt:'TrustRadius & Converseon interlock (60 min, Zoom): IBM Dashboard strategy. TrustRadius & Converseon interlock _ IBM Dashboard. Decision-maker alignment secured. Weflow rec: a76RN... (May 13 15:00)', csmlbl:'Augie Buettner',      change:'New &middot; Note 9c7a5f03' },
    { ae:'mark',     health:'Healthy',    account:'Adobe Systems',        opp:'Deal Note &mdash; May 13 (Monthly + Success)', arr:'Enterprise AE &middot; Mark Fell',           excerpt:'Two sessions (90 min total): Monthly strategic sync (60 min, 3:00 PM) — data strategy and product roadmap. TrustRadius success call (30 min, 5:00 PM) — review performance and campaign progress. Multi-thread engagement strong. Weflow recs: a76RN... × 2', csmlbl:'Mark Fell',           change:'New &middot; Notes 3d9e7b55 / a1f4c290' },
    { ae:'adrian',   health:'Healthy',    account:'Hitachi Vantara',      opp:'Deal Note &mdash; May 13 EBR',              arr:'Enterprise AE &middot; Adrian Escobar',          excerpt:'Executive Business Review (60 min, Zoom): Account health strong. Expansion discussion active. HG Insights / Hitachi EBR. Weflow rec: a76RN... (May 13 15:15)', csmlbl:'Adrian Escobar',      change:'New &middot; Note 8b3c6d77' },
    { ae:'leo',      health:'Healthy',    account:'Thomson Reuters',      opp:'Deal Note &mdash; May 13 Data Review',      arr:'Enterprise AE &middot; Leo Zunz',               excerpt:'Data review session (60 min, Zoom): Data quality alignment and HG pipeline review. HG Insights x Thomson Reuters | Data Review. No transcript at scan time — confirmed call with timestamp. Weflow rec: a76RN... (May 13 15:30)', csmlbl:'Leo Zunz',            change:'New &middot; Note 4f2a8e16' },
    { ae:'mark',     health:'Healthy',    account:'Google Inc',           opp:'Deal Note &mdash; May 13 (3 Sessions)',     arr:'Enterprise AE &middot; Mark Fell',              excerpt:'Three sessions (90 min total): Technical connect 4:00 PM (30 min), TrustRadius connect 5:30 PM (30 min, no transcript), Weekly strategic sync 7:00 PM (30 min). High-touch account — Google + HG data partnership momentum. Weflow recs: a76RN... × 3', csmlbl:'Mark Fell',           change:'New &middot; Notes 6c1b5a88 / e7d2f043 / b9a3c125' },
    { ae:'leo',      health:'Healthy',    account:'Iron Mountain',        opp:'Deal Note &mdash; May 13 Account Sync',     arr:'Enterprise AE &middot; Leo Zunz',               excerpt:'Account sync (30 min, Zoom): Data usage review and renewal alignment in progress. HG Insights - IRM. Weflow rec: a76RN... (May 13 16:30)', csmlbl:'Leo Zunz',            change:'New &middot; Note 2e5d9f34' },
    { ae:'anderson', health:'Healthy',    account:'ZScaler',              opp:'Deal Note &mdash; May 13 TR CSM Sync',      arr:'Enterprise AE &middot; Anderson Duncan',        excerpt:'TrustRadius CSM sync (30 min, Zoom): Review program status and campaign planning. ZScaler <> TrustRadius CSM Syncs. No transcript at scan time — confirmed call with timestamp. Weflow rec: a76RN... (May 13 17:00)', csmlbl:'Anderson Duncan',     change:'New &middot; Note 7g4h2k91' },
    { ae:'ziad',     health:'Concerning', account:'Salesforce Inc',       opp:'Deal Note &mdash; May 13 MadKudu Blocker',  arr:'Enterprise AE &middot; Ziad Amira',             excerpt:'MadKudu integration (30 min, Zoom): Blocker preventing connection to Salesforce CRM is essential for MadKudu scoring and predictive modeling. Snowflake explored as alternative data integration method. Requires resolution to unlock revenue intelligence use case. Weflow rec: a76RN... (May 13 17:00)', csmlbl:'Ziad Amira',          change:'New &middot; Note 3k9m1p56' },
    { ae:'ziad',     health:'Healthy',    account:'Okta Ventures',        opp:'Deal Note &mdash; May 13 Review Campaign',  arr:'Enterprise AE &middot; Ziad Amira',             excerpt:'Review incentive campaign (30 min, Zoom): $50 incentive set, TrustRadius review widget integration on website planned. Wrike | TrustRadius (linked to Okta Ventures). Campaign launch imminent. Weflow rec: a76RN... (May 13 17:00)', csmlbl:'Ziad Amira',          change:'New &middot; Note 8n2q7r03' },
    { ae:'ziad',     health:'Healthy',    account:'F5',                   opp:'Deal Note &mdash; May 13 TR Sync',          arr:'Enterprise AE &middot; Ziad Amira',             excerpt:'TrustRadius sync (30 min, Zoom): Review program status and campaign updates discussed. F5 - TrustRadius Sync. No transcript at scan time — confirmed call with timestamp. Weflow rec: a76RN... (May 13 17:30)', csmlbl:'Ziad Amira',          change:'New &middot; Note 5p3s9t71' },
    { ae:'ravi',     health:'Healthy',    account:'Workday Inc',          opp:'Deal Note &mdash; May 13 Kendall Update',   arr:'Enterprise AE &middot; Ravi Sharma',            excerpt:'Kendall call update (30 min, Zoom): HG Insights / Workday - update from call with Kendall. Account status reviewed, pipeline alignment confirmed. Weflow rec: a76RN... (May 13 18:30)', csmlbl:'Ravi Sharma',         change:'New &middot; Note 1v8w4x29' },
    { ae:'adrian',   health:'Healthy',    account:'Autodesk Inc',         opp:'Deal Note &mdash; May 13 Bi-weekly Sync',   arr:'Enterprise AE &middot; Adrian Escobar',         excerpt:'Bi-weekly sync (30 min, Zoom): Account check-in and pipeline review. HGI + Autodesk <> Bi Weekly Sync. No transcript at scan time — confirmed call with timestamp. Weflow rec: a76RN... (May 13 19:00)', csmlbl:'Adrian Escobar',      change:'New &middot; Note 6y2z5a47' },
    { ae:'ziad',     health:'Healthy',    account:'Docusign',             opp:'Deal Note &mdash; May 13 Data Dictionary',  arr:'Enterprise AE &middot; Ziad Amira',             excerpt:'Data dictionary vs test file (30 min, Zoom): Data quality alignment and validation review. No transcript at scan time — confirmed call with timestamp. Weflow rec: a76RN... (May 13 21:00)', csmlbl:'Ziad Amira',          change:'New &middot; Note 9b7c3d64' },
  ];
  const bc = h => h==='Healthy'?'badge-healthy':'badge-concerning';
  const bi = h => h==='Healthy'?'&#128994;':'&#128993;';
  return `<div class="pulse-grid">${cards.map(c=>`
    <div class="pulse-card" data-ae="${c.ae}" data-health="${c.health}">
      <div class="pulse-card-top"><div><div class="pulse-account">${c.account}</div><div class="pulse-opp">${c.opp}</div><div class="pulse-arr">${c.arr}</div></div><span class="badge ${bc(c.health)}">${bi(c.health)} ${c.health}</span></div>
      <div class="pulse-excerpt">${c.excerpt}</div>
      <div class="pulse-footer"><span>${c.csmlbl}</span><span>${c.change}</span></div>
    </div>`).join('')}</div>
  <div class="empty-state" id="pulses-empty" style="display:none"><div class="empty-icon">&#128269;</div>No notes match these filters.</div>`;
}

function dayActionsHTML_2026_05_13() {
  return `<div class="action-list">
    <div class="action-item ${doneActions.has(1301)?'done':''}" data-ae="ziad" id="action-1301"><div class="action-checkbox ${doneActions.has(1301)?'checked':''}" onclick="toggleAction(1301)"></div><div class="action-body"><div class="action-title">&#x26a0;&#xfe0f; Salesforce Inc &mdash; MadKudu CRM connection blocker (Ziad Amira)</div><div class="action-meta"><span class="urgency-badge urgency-high">HIGH PRIORITY</span>Ziad Amira &middot; Salesforce CRM connection to MadKudu is blocked, preventing scoring and predictive modeling (win/loss data requirement). Snowflake explored as alternative (May 13 call, 30 min). Next step: confirm whether Snowflake integration is viable or escalate to technical team. Blocker must be resolved to unlock the intelligence use case for this account.</div></div></div>
    <div class="action-item ${doneActions.has(1302)?'done':''}" data-ae="hayden" id="action-1302"><div class="action-checkbox ${doneActions.has(1302)?'checked':''}" onclick="toggleAction(1302)"></div><div class="action-body"><div class="action-title">&#x1F3E2; Intuit onsite follow-up &mdash; next steps and use case recap</div><div class="action-meta"><span class="urgency-badge urgency-high">TIME-SENSITIVE</span>Hayden Smith &middot; Intuit HG Onsite (May 13, 60 min) covered use case deep dive with strategic alignment. Capture the specific use cases discussed while top of mind. Send follow-up with agreed next steps, timeline, and any data requests surfaced during the session. Momentum from onsite should drive near-term action.</div></div></div>
    <div class="action-item ${doneActions.has(1303)?'done':''}" data-ae="mark" id="action-1303"><div class="action-checkbox ${doneActions.has(1303)?'checked':''}" onclick="toggleAction(1303)"></div><div class="action-body"><div class="action-title">&#x1F4CB; Google Inc &mdash; 3-session recap needed (Mark Fell)</div><div class="action-meta"><span class="urgency-badge urgency-medium">MEDIUM</span>Mark Fell &middot; Google had three separate Weflow recordings on May 13: technical connect (4:00 PM), TrustRadius connect (5:30 PM, no transcript), and weekly strategic sync (7:00 PM). Consolidate key takeaways across all three sessions into a single deal note. Confirm what was covered in the 5:30 PM recording once transcript is available.</div></div></div>
    <div class="action-item ${doneActions.has(1304)?'done':''}" data-ae="anderson" id="action-1304"><div class="action-checkbox ${doneActions.has(1304)?'checked':''}" onclick="toggleAction(1304)"></div><div class="action-body"><div class="action-title">&#x23F3; ZScaler transcript pending &mdash; Anderson Duncan</div><div class="action-meta"><span class="urgency-badge urgency-low">FOLLOW-UP</span>Anderson Duncan &middot; ZScaler (May 13, 5:00 PM, 30 min) had no transcript at scan time. Check Weflow once transcript processes. Confirm call content and update deal note with specifics on review program status and campaign next steps.</div></div></div>
  </div>
  <div class="empty-state" id="actions-empty" style="display:none"><div class="empty-icon">&#128269;</div>No action items match these filters.</div>`;
}
